### ISSUE TITLE
Mix van JS coding stylen

### ISSUE THREAD

**Issue by KoopReynders** [Matthijs217/fix-the-flow-interactive-website#8]
Je gebruikt nu verschillende javascript notatie door elkaar heen. 
Dit is bijvoorbeeld een shorthand (wordt gebruikt sinds ES6): 

https://github.com/Matthijs217/fix-the-flow-interactive-website/blob/000047d852ebcbd9db8fcb4157dd373b83573d00/scripts/main-page.js#L38

Kan jij dit al zelf? 

Probeer dit eens uit te schrijven in dezelfde coding style als de rest van je script. 
Dan wordt het ook meer leesbaar. En dat is weer handig voor de code review...

**Comment by Matthijs217** [comment]
Ik heb dit geleerd tijdens de JavaScript challenge, daarin werd er verteld dat dit een andere manier is voor if else. Daarom had ik dit gebruikt omdat het makkelijker was

**Comment by KoopReynders** [comment]
Goed bezig Matthijs
🚀
